# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-10 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0004_employee_sv_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sv_nr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
