# Generated by Django 2.0.3 on 2019-02-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0006_auto_20180310_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='event',
            field=models.IntegerField(null=True),
        ),
    ]
