# Generated by Django 2.0.3 on 2019-02-15 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0009_auto_20190215_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='event',
            name='lm_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='timeTracker.Event', to_field='lm_id'),
        ),
    ]
