# Generated by Django 2.2.24 on 2021-11-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0010_auto_20190215_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterField(
            model_name='shift',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='timeTracker.Event', to_field='lm_id'),
        ),
        migrations.CreateModel(
            name='MessageConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timeTracker.Employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timeTracker.Shift')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('confirmation_required', models.BooleanField(default=False)),
                ('reoccuring', models.BooleanField(default=False)),
                ('employee', models.ManyToManyField(blank=True, null=True, to='timeTracker.Employee')),
            ],
        ),
    ]
