# Generated by Django 2.2.24 on 2021-11-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0011_auto_20211105_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='employee',
            field=models.ManyToManyField(blank=True, to='timeTracker.Employee'),
        ),
    ]
