# Generated by Django 2.2.24 on 2021-11-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0012_auto_20211105_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sv_nr',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
