# Generated by Django 2.2.24 on 2021-11-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0014_message_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='employee',
            new_name='employees',
        ),
    ]
