# Generated by Django 2.2.24 on 2021-11-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0015_auto_20211105_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageconfirmation',
            name='employee',
        ),
    ]
